new (git): logs de deploy da aplicação

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,6 +63,7 @@ jobs:
 
     # fora do marketplace : https://github.com/awslabs/amazon-app-runner-deploy
     - name: Deploy to App Runner
+      id: deploy-to-apprunner
       uses: awslabs/amazon-app-runner-deploy@main
       with:
         service: rocketseat-ci-api
@@ -72,7 +73,17 @@ jobs:
         memory: 2
         port: 3000
         image: ${{ steps.build-docker-image.outputs.image }}
+        wait-for-service-stability: true
     
+    - name: Check deployment status
+      run: |
+        STATUS=$(aws apprunner describe-service --service-arn arn:aws:apprunner:us-east-2:132466043431:service/rocketseat-ci-api/1234567890123 --query 'Service.Status' --output text)
+        echo "Deployment Status: $STATUS"
+        if [ "$STATUS" != "RUNNING" ]; then
+          echo "Deployment failed or is not running."
+          exit 1
+        fi
+    # echo "Deployment succeeded and is running. ${{ steps.deploy-to-apprunner.outputs.service-url }}"
     # Alternativa para o login no ECR
     # - name: Build ECR image
     #   run: |
